config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mailing

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingList, MailingCreateView, MailingLogList, MailingDetailView, MailingUpdateView, \
    MailingDeleteView, CustomerCreateView, CustomerUpdateView, CustomerList, CustomerDetailView, CustomerDeleteView

app_name = MailingConfig.name


urlpatterns = [
    path('', MailingList.as_view(), name='index'),
    path('mailinglog_list/', MailingLogList.as_view(), name='mailinglog_list'),
    path('customer_list/', CustomerList.as_view(), name='customer_list'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('create_customer/', CustomerCreateView.as_view(), name='create_customer'),
    path('mailing/view/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('customer/view/<int:pk>', CustomerDetailView.as_view(), name='customer_detail'),
    path('mailing/edit/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('customer/edit/<int:pk>', CustomerUpdateView.as_view(), name='customer_update'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(), name='customer_delete')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),


]

mailing/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    email = models.EmailField(max_length=100, verbose_name='email', unique=True)
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f"email: {self.email}, ФИО: {self.full_name}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    time = models.DateTimeField(verbose_name='время рассылки')
    period = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность', **NULLABLE)
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус рассылки', **NULLABLE)

    theme = models.CharField(max_length=150, verbose_name='тема')
    mailing_text = models.TextField(verbose_name='текст письма', **NULLABLE)

    customer = models.ManyToManyField(Customer, max_length=150, verbose_name='клиент')

    def __str__(self):
        return f'theme: {self.theme}, period: {self.period}, status: {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'

    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    last_try = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    last_try_status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_OK)
    customer = models.ForeignKey(Customer, max_length=150, verbose_name='клиент', on_delete=models.CASCADE)
    mailing = models.ForeignKey(Mailing, max_length=150, verbose_name='рассылка', on_delete=models.CASCADE)
    error_msg = models.TextField(verbose_name='error message', **NULLABLE)

    def __str__(self):
        return f'{self.mailing} {self.last_try} {self.last_try_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Customer

from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            elif isinstance(field.widget, forms.widgets.PasswordInput):
                field.widget.attrs['class'] = 'form-control'

            else:
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = '__all__'


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'

mailing/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from mailing.forms import MailingForm, CustomerForm
from mailing.models import Mailing, MailingLog, Customer


class MailingList(ListView):
    model = Mailing

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mailing List'
        return context


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:index')


class MailingLogList(ListView):
    model = MailingLog
    template_name = 'mailing/mailinglog_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(mailing__status=Mailing.STATUS_DONE)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mailing Logs  List'
        return context


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing_detail', args=[self.kwargs.get('pk')])


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:index')


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm

    success_url = reverse_lazy('mailing:index')


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm

    success_url = reverse_lazy('mailing:index')


class CustomerList(ListView):
    model = Customer

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Customer List'
        return context


class CustomerDetailView(DetailView):
    model = Customer


class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy('mailing:customer_list')

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'mailing/css/bootstrap.min.css'%} " rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Menu</h4>
          <ul class="list-unstyled">
            <li><a href="{% url 'mailing:customer_list' %}" class="text-white">List of Customers</a></li>
            <li><a href="{% url 'mailing:mailinglog_list' %}" class="text-white">List of Mailing logs</a></li>
              {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}" class="text-white"> Logout</a></li>
              {% else %}
                  <li><a href="{% url 'users:login' %}" class="text-white">Login</a></li>
                  <li><a href="{% url 'users:register' %}" class="text-white">Registration</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'mailing:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Main Page</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">{{ title }}</h1>
        <p>
          <a href="{% url 'mailing:create_customer' %}" class="btn btn-primary my-2">Create Customer</a>
          <a href="{% url 'mailing:create_mailing' %}" class="btn btn-secondary my-2">Create Mailing</a>
        </p>
      </div>
    </div>
  </section>
    {% block content %}

    {% endblock %}
</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="{% static 'mailing/js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

mailing/templates/mailing/customer_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пользователя "{{ object.full_name }}"?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:customer_list' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/customer_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
        {% include 'mailing/includes/inc_customer.html' %}
{% endblock %}

mailing/templates/mailing/customer_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card-header">
            <div class="card-title">
                <h2>Добавить пользователя</h2>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать пользователя
                        {% endif %}
                    </button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</form>
</div>
{% endblock %}

mailing/templates/mailing/customer_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
    <a class="btn btn-primary" href="{% url 'mailing:create_customer' %}">Создать пользователя</a>
    </div>
    <div class="container">
    <div class="row">
    {% for object in object_list %}
  {% include 'mailing/includes/inc_customer.html' %}
    {% endfor %}
    </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.theme }}"?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:index' %}">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
        {% include 'mailing/includes/inc_mailing.html' %}
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card-header">
            <div class="card-title">
                <h2>Добавление рассылки</h2>
            </div>
            <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать рассылку
                        {% endif %}
                    </button>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
    <div class="row">
    {% for object in object_list %}
  {% include 'mailing/includes/inc_mailing.html' %}
    {% endfor %}
    </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailinglog_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
    <div class="row">
    {% for object in object_list %}
  {% include 'mailing/includes/inc_mailinglog.html' %}
    {% endfor %}
    </div>
    </div>
{% endblock %}