config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mailing

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingList, MailingCreateView, MailingLogList, MailingDetailView, MailingUpdateView, \
    MailingDeleteView, CustomerCreateView, CustomerUpdateView, CustomerList, CustomerDetailView, CustomerDeleteView

app_name = MailingConfig.name


urlpatterns = [
    path('', MailingList.as_view(), name='index'),
    path('mailinglog_list/', MailingLogList.as_view(), name='mailinglog_list'),
    path('customer_list/', CustomerList.as_view(), name='customer_list'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('create_customer/', CustomerCreateView.as_view(), name='create_customer'),
    path('mailing/view/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('customer/view/<int:pk>', CustomerDetailView.as_view(), name='customer_detail'),
    path('mailing/edit/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('customer/edit/<int:pk>', CustomerUpdateView.as_view(), name='customer_update'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('customer/delete/<int:pk>', CustomerDeleteView.as_view(), name='customer_delete')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),


]

mailing/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    email = models.EmailField(max_length=100, verbose_name='email', unique=True)
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return f"email: {self.email}, ФИО: {self.full_name}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    time = models.DateTimeField(verbose_name='время рассылки')
    period = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность', **NULLABLE)
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус рассылки', **NULLABLE)

    theme = models.CharField(max_length=150, verbose_name='тема')
    mailing_text = models.TextField(verbose_name='текст письма', **NULLABLE)

    customer = models.ManyToManyField(Customer, max_length=150, verbose_name='клиент')

    def __str__(self):
        return f'theme: {self.theme}, period: {self.period}, status: {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'

    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    last_try = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    last_try_status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_OK)
    customer = models.ForeignKey(Customer, max_length=150, verbose_name='клиент', on_delete=models.CASCADE)
    mailing = models.ForeignKey(Mailing, max_length=150, verbose_name='рассылка', on_delete=models.CASCADE)
    error_msg = models.TextField(verbose_name='error message', **NULLABLE)

    def __str__(self):
        return f'{self.mailing} {self.last_try} {self.last_try_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms

from mailing.models import Mailing, Customer

from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():

            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            elif isinstance(field.widget, forms.widgets.PasswordInput):
                field.widget.attrs['class'] = 'form-control'

            else:
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        fields = '__all__'


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'

mailing/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from mailing.forms import MailingForm, CustomerForm
from mailing.models import Mailing, MailingLog, Customer


class MailingList(ListView):
    model = Mailing

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mailing List'
        return context


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:index')


class MailingLogList(ListView):
    model = MailingLog
    template_name = 'mailing/mailinglog_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(mailing__status=Mailing.STATUS_DONE)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mailing Logs  List'
        return context


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing_detail', args=[self.kwargs.get('pk')])


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:index')


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm

    success_url = reverse_lazy('mailing:index')


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm

    success_url = reverse_lazy('mailing:index')


class CustomerList(ListView):
    model = Customer

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Customer List'
        return context


class CustomerDetailView(DetailView):
    model = Customer


class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy('mailing:customer_list')

mailing/templates/mailing/includes/inc_customer.html
<div class="container">
    <div class="row">
    <div class="col-12 card mb-5 text-center" style="max-width: 300px">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ object.full_name }}</h5>
            <p class="card-text"><strong>Email:</strong> {{ object.email }}</p>
            <p class="card-text"><strong>Комментарий:</strong> {{ object.comment }}</p>
        </div>
        <div class="card-footer">
        <div class="btn-group">
            <a href="{% url 'mailing:customer_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
            <a href="{% url 'mailing:customer_update' object.pk%}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
            <a href="{% url 'mailing:customer_delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
        </div>
    </div>
    </div>
</div>
</div>
</div>

mailing/templates/mailing/includes/inc_mailing.html
<div class="col-12 card mb-5 text-center" style="max-width: 300px">
<div class="row">
    <div class="col-md-8">
            <div class="card-header">
            <h5 class="card-title">{{ object.theme }}</h5>
            <p class="card-text"><strong>Периодичность:</strong> {{ object.period }}</p>
            <p class="card-text"><strong>Статус:</strong> {{ object.status }}</p>
            <p class="card-text"><strong>Время рассылки:</strong> {{ object.time }}</p>
            </div>
             <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Клиенты:</h6>
            <ul class="list-unstyled">
                {% for customer in object.customer.all %}
                    <li>{{ customer.name }} - {{ customer.email }}</li>
                {% endfor %}
            </ul>
            <h6 class="card-subtitle mb-2 text-muted">Сообщение:</h6>
            <p class="card-text">{{ object.mailing_text }}</p>
        </div>
    <div class="card-footer">
        <div class="btn-group">
            <a href="{% url 'mailing:mailing_detail' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
            <a href="{% url 'mailing:mailing_update' object.pk%}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
            <a href="{% url 'mailing:mailing_delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
        </div>
    </div>
    </div>
</div>
</div>

mailing/templates/mailing/includes/inc_mailinglog.html
<!-- Ваш HTML-код и начало цикла для итерации по объектам MailingLog -->
<div class="container">
  <div class="row">
    {% for log in object_list %}
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-header">
          {{ log.mailing.theme }}
        </div>
        <div class="card-body">
          <p class="card-text">Дата и время: {{ log.last_try }}</p>
          <p class="card-text">Статус: {{ log.get_last_try_status_display }}</p>
          <p class="card-text">Клиент: {{ log.customer.full_name }}</p>
          <p class="card-text">Рассылка: {{ log.mailing.theme }}</p>
          <p class="card-text">Error Message: {{ log.error_msg }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Завершение цикла и другой HTML-код -->